### ISSUE TITLE
Display negative values

### ISSUE THREAD

**Issue by urmi1** [dral3x/SPChart#2]
Hi..

How can i display negative values in bar chart?

**Comment by dral3x** [comment]
In the latest version of the library, you can have upside down bar charts. Positive values are still required.
Not sure if this can help you.

**Comment by thom-ek** [comment]
Support for negative values is at my pull request https://github.com/dral3x/SPChart/pull/5.

**Comment by dral3x** [comment]
Thanks for that!

I'll release version 0.3.1 asap 👍
