### ISSUE TITLE
Change X Labels orientation

### ISSUE THREAD

**Issue by ecaste** [dral3x/SPChart#3]
Hi,
love your librairie ! Thank you
Could you add support for rotating x labels ?  I would like to be able to do this kind of stuff :
![1](https://cloud.githubusercontent.com/assets/713476/5917222/a49eb164-a61a-11e4-962d-946899e37ab8.png)
Thanks !
Emmanuel

**Comment by dral3x** [comment]
Hello there,
should not be hard to do it. Just applying a rotation transform on labels.

If you do that, I'll love to accept a pull request with that :+1: 
Alessandro

**Comment by ecaste** [comment]
:) it's what I've done, but to be honest I'm not using git for a long time, and don't know how to make a pull request properly. Perhaps you could give me 2/3 words in private to help me? Thanks

**Comment by dral3x** [comment]
Sure! Contact me by email or twitter, as you prefer.
My contacts are in [here](http://about.me/alessandro.calzavara) :)
